spring:
  application:
    name: "takehome"
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:user"
    username: "h2mem"
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: "warn"
    com.continentcountry.TakehomeApplication: "warn"
